Repository 3scale/3scale-operator, pull requests merged in 2023-09, with the labels that each got.

#854 MGDAPI-5887 - apis go module - refactoring
  apis/apps/common.go
  apis/apps/v1alpha1/apimanager_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/capabilities/v1beta1/activedoc_types.go
  apis/capabilities/v1beta1/application_types.go
  apis/capabilities/v1beta1/backend_types.go
  apis/capabilities/v1beta1/custompolicydefinition_types.go
  apis/capabilities/v1beta1/developeraccount_types.go
  apis/capabilities/v1beta1/developeruser_types.go
  apis/capabilities/v1beta1/openapi_types.go
  apis/capabilities/v1beta1/product_types.go
  apis/capabilities/v1beta1/proxyconfigpromote_types.go
  apis/capabilities/v1beta1/zz_generated.deepcopy.go
  controllers/apps/apimanager_controller_test.go
  controllers/apps/apimanager_status_reconciler.go
  controllers/capabilities/activedoc_status_reconciler.go
  controllers/capabilities/application_status_reconciler.go
  controllers/capabilities/application_status_reconciler_test.go
  controllers/capabilities/backend_status_reconciler.go
  controllers/capabilities/custompolicydefinition_status_reconciler.go
  controllers/capabilities/developeraccount_status_reconciler.go
  controllers/capabilities/developeruser_status_reconciler.go
  controllers/capabilities/openapi_status_reconciler.go
  controllers/capabilities/product_status_reconciler.go
  controllers/capabilities/proxyconfigpromote_controller_test.go
  controllers/capabilities/proxyconfigpromote_status_reconciler.go
  controllers/capabilities/proxyconfigpromote_status_reconciler_test.go
  pkg/3scale/amp/component/apicast.go
  pkg/3scale/amp/component/system.go
  pkg/3scale/amp/component/system_options.go
  pkg/3scale/amp/operator/apicast_options_provider.go
  pkg/3scale/amp/operator/apicast_options_provider_test.go
  pkg/3scale/amp/operator/apicast_reconciler_test.go
  pkg/3scale/amp/operator/system_options_provider.go
  pkg/3scale/amp/operator/system_options_provider_test.go
  pkg/3scale/amp/prometheusrules/apicast_rules.go
  pkg/apispkg/common/status_conditions.go
  pkg/apispkg/helper/email.go
  pkg/controller/helper/backend_list_test.go
  pkg/controller/helper/product_list_test.go
  test/unitcontrollers/apimanager_controller_test.go
Labels: lgtm, approve

#863 THREESCALE-10092 refactor status reporting on proxyConfigPromote
  apis/capabilities/v1beta1/proxyconfigpromote_types.go
  controllers/capabilities/application_controller_test.go
  controllers/capabilities/application_status_reconciler_test.go
  controllers/capabilities/applications_test.go
  controllers/capabilities/proxyconfigpromote_controller.go
  controllers/capabilities/proxyconfigpromote_controller_test.go
  controllers/capabilities/proxyconfigpromote_status_reconciler.go
  controllers/capabilities/proxyconfigpromote_status_reconciler_test.go
Labels: verified, lgtm

#861 Threescale 6735 - Reconcile Secrets (replace PR 845)
  controllers/apps/apimanager_controller.go
  controllers/apps/secret_to_apimanager_event_mapper.go
  doc/adding-custom-policies.md
  main.go
  pkg/3scale/amp/component/apicast.go
  pkg/3scale/amp/component/apicast_options.go
  pkg/3scale/amp/operator/apicast_options_provider.go
  pkg/3scale/amp/operator/apicast_options_provider_test.go
  pkg/3scale/amp/operator/apicast_reconciler.go
  pkg/3scale/amp/operator/apicast_reconciler_test.go
  pkg/3scale/amp/operator/apimanager_utils.go
  pkg/3scale/amp/prometheusrules/apicast_rules.go
Labels: lgtm, approve

#865 THREESCALE-8128 remove unnecesary camel case removal
  apis/capabilities/v1beta1/backend_types.go
  apis/capabilities/v1beta1/product_types.go
  pkg/helper/openapi_utils.go
Labels: lgtm, approve

#869 THREESCALE-10162 add skip insecure verify to OpenAPI backend and product
  controllers/capabilities/openapi_backend_reconciler.go
  controllers/capabilities/openapi_product_reconciler.go
  doc/openapi-reference.md
  doc/operator-user-guide.md
Labels: lgtm, approve

#875 toc-test
  Makefile
  doc/openapi-reference.md
  doc/openapi-user-guide.md
  doc/operator-application-capabilities.md
  doc/operator-user-guide.md
Labels: lgtm
