Repository 3scale/3scale-operator, pull requests merged in 2024-01, with the labels that each got.

#900 THREESCALE-10381 ProxyConfigPromote CR - improve config to stage promotion
  controllers/capabilities/proxyconfigpromote_controller.go
  controllers/capabilities/proxyconfigpromote_controller_test.go
Labels: ok-to-test

#907 Update system Grafana dashboard to adjust to changes in reported metrics
  pkg/assets/assets/monitoring/system-grafana-dashboard-1.json.tpl
  pkg/assets/bindata.go
Labels: lgtm, approve

#919 THREESCALE-10693 set maxOpenShiftVersion to 4.15
  Makefile
  bundle/manifests/3scale-operator.clusterserviceversion.yaml
  config/manifests/bases/3scale-operator.clusterserviceversion.yaml
Labels: /lgtm
